config/routes.rb
Rails.application.routes.draw do
  resources :apps do
    member do
      get 'latest_version'
    end
    
    resources :app_files do
      get 'build_log'
      get 'download'
    end
  end

  get 'sessions/signin'
  post 'sessions/create'
  get 'sessions/create_during_test'
  post 'sessions/destroy'

  get '/auth/:provider/callback', to: 'sessions#oauth_create'

  root 'apps#index'

end

app/models/app_file.rb
class AppFile < ActiveRecord::Base
  belongs_to :app
  belongs_to :user

  validates :app, presence: true
  validates_inclusion_of :platform, :in => %w( Android iOS )
  validates :version, presence: true

  has_attached_file :archive
  validates_attachment_file_name :archive, matches: [/apk\Z/, /zip\Z/]
  validates_with AttachmentPresenceValidator, attributes: :archive, :on => :create
  validates_with AttachmentSizeValidator, attributes: :archive, less_than: 300.megabytes

  enum code_signing_status: { unsigned: 0, downloading_to_mac: 4, signing: 1, signing_failed: 2, pending_transfer_to_web: 5, downloading_to_web: 6, download_to_web_failed: 7, signed: 3 }
  after_commit :queue_for_ios_code_signing, :on => :create

  def signed_ipa_location
    File.join(File.dirname(archive.path), 'Signed.ipa')
  end

  def queue_for_ios_code_signing
    puts "code_signing_status = " + code_signing_status
    puts "platform = " + platform
    puts "id = " + id.to_s
    if is_ios_app?
      # make a secret random key for direct download
      require 'securerandom'
      update_column(:download_token, SecureRandom.hex)

      BuildIpaJob.perform_later id
    end
  end

  def is_ios_app?
    platform == "iOS"
  end

  def is_android_app?
    platform == "Android"
  end

  def itms_services_url
    unless is_ios_app?
      raise "Only iOS apps have itms-services URLs"
    end

    url_options = Rails.application.config.action_mailer.default_url_options
    url_options[:format] = :plist
    url_options[:protocol] = :https
    'itms-services://?action=download-manifest&url=' + Rails.application.routes.url_helpers.app_app_file_download_url(app, self, url_options)
  end

  def apk_url
    unless is_android_app?
      raise "Only Android apps have apk_url"
    end

    url_options = Rails.application.config.action_mailer.default_url_options
    url_options[:format] = :apk
    url_options[:protocol] = :https
    Rails.application.routes.url_helpers.app_app_file_download_url(app, self, url_options)
  end

end

app/controllers/app_files_controller.rb
class AppFilesController < ApplicationController
  before_action :set_app_file, only: [:show, :edit, :update, :destroy]

  # GET /app_files
  # GET /app_files.json
  def index
    @app_files = AppFile.where(app_id: params[:app_id])
  end

  # GET /app_files/1
  # GET /app_files/1.json
  def show
    authorize @app_file
  end

  # GET /app_files/1/download
  def download
    @app_file = AppFile.find(params[:app_file_id])
    respond_to do |format|
      format.zip do
        if params[:download_token] == @app_file.download_token
          send_file @app_file.archive.path
        else
          head :bad_request
        end
      end

      format.apk do
        send_file @app_file.archive.path
        increment_download_count
      end

      format.plist do
        if @app_file.signed?
          render 'manifest.plist'
        else
          render json: { :error => 'Signed ipa is not available yet' }, status: :bad_request
        end
        increment_download_count
      end

      format.ipa do
        if @app_file.signed?
          send_file @app_file.signed_ipa_location, :type => 'application/octet-stream'
        else
          render json: { :error => 'Signed ipa is not available yet' }, status: :bad_request
        end
      end
    end
  end

  def build_log
    @app_file = AppFile.find(params[:app_file_id])
    authorize @app_file, :edit?
    render plain: @app_file.code_signing_log
  end

  # GET /app_files/new
  def new
    @app_file = AppFile.new
    @app_file.app_id = params[:app_id]
    authorize @app_file
  end

  # GET /app_files/1/edit
  def edit
    authorize @app_file
  end

  # POST /app_files
  # POST /app_files.json
  def create
    @app_file = AppFile.new(app_file_params)
    @app_file.app_id = params[:app_id]

    authorize @app_file

    respond_to do |format|
      if @app_file.save
        format.html { redirect_to @app_file.app, notice: 'App file has been uploaded.' }
        format.json { render :show, status: :created, location: @app_file }

        SendSlackUpdateJob.perform_later "[!!] %s uploaded [%s](%s) (ver. %s for %s) <!channel>" \
          % [if current_user.nil? then 'Guest' else current_user.display_name end, @app_file.app.name, app_url(@app_file.app), @app_file.version, @app_file.platform].map { |s| SlackNotifier.escape(s.to_s) }
      else
        format.html { render :new }
        format.json { render json: @app_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /app_files/1
  # PATCH/PUT /app_files/1.json
  def update
    authorize @app_file
    respond_to do |format|
      if @app_file.update(app_file_params)
        format.html { redirect_to @app_file, notice: 'App file was successfully updated.' }
        format.json { render :show, status: :ok, location: @app_file }
      else
        format.html { render :edit }
        format.json { render json: @app_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /app_files/1
  # DELETE /app_files/1.json
  def destroy
    authorize @app_file
    @app_file.destroy
    respond_to do |format|
      format.html { redirect_to app_app_files_url(@app_file.app), notice: 'App file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def increment_download_count
      # ignore HEAD requests
      if request.head?
        return
      end

      unless request.headers['Range'].nil?
        # ignore request if Range header exists and starting range is not 0
        range = request.headers['Range'].match(/bytes=(?<begin>\d+)-(?<end>\d*)/)
        if range[:begin] != '0'
          return
        end
      end
      
      @app_file.increment!(:download_count)

      SendSlackUpdateJob.perform_later "%s (IP: %s) downloaded [%s](%s) (ver. %s for %s)" \
        % [if current_user.nil? then 'Guest' else current_user.display_name end, request.remote_ip, @app_file.app.name, app_url(@app_file.app), @app_file.version, @app_file.platform].map { |s| SlackNotifier.escape(s.to_s) }
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_app_file
      @app_file = AppFile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def app_file_params
      params.require(:app_file).permit(:platform, :version, :archive, :app_id)
    end
end

app/helpers/app_files_helper.rb
module AppFilesHelper
end

app/views/app_files/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%= simple_form_for([@app_file.app, @app_file]) do |f| %>
      <%= f.input :platform, collection: ['iOS', 'Android'], as: :radio_buttons, required: true %>
      <%= f.input :version, required: true %>
      <%= f.input :archive, as: :file, required: true %>
      <%= f.button :submit, 'Upload New App Release' %>
    <% end %>
  </div>
</div>

app/views/app_files/edit.html.erb
<h1>Editing App File</h1>

<%= render 'form' %>

<%= link_to 'Show', @app_file %> |
<%= link_to 'Back', app_files_path %>

app/views/app_files/index.html.erb
<h1>Listing App Files</h1>

<table class="table">
  <thead>
    <tr>
      <th>Platform</th>
      <th>Version</th>
      <th>Download count</th>
      <th>App signing</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @app_files.each do |app_file| %>
      <tr>
        <td><%= app_file.platform %></td>
        <td><%= app_file.version %></td>
        <td><%= app_file.download_count %></td>
        <td><%= app_file.code_signing_status %> (<%= link_to 'View log', app_app_file_build_log_path(app_file.app, app_file) %>)</td>
        <td><%= link_to 'Edit', edit_app_app_file_path(app_file.app, app_file) %></td>
        <td><%= link_to 'Destroy', app_app_file_path(app_file.app, app_file), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<br>

app/views/app_files/manifest.plist.erb
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>items</key>
    <array>
        <dict>
            <key>assets</key>
            <array>
                <dict>
                    <key>kind</key>
                    <string>software-package</string>
                    <key>url</key>
                    <string><%= app_app_file_download_url(@app_file.app, @app_file, protocol: 'https', format: :ipa) %></string>
                </dict>
            </array>
            <key>metadata</key>
            <dict>
                <key>bundle-identifier</key>
                <string><%= @app_file.app.ios_application_identifier %></string>
                <key>bundle-version</key>
                <string><%= @app_file.version %></string>
                <key>kind</key>
                <string>software</string>
                <key>title</key>
                <string><%= @app_file.app.name %></string>
            </dict>
        </dict>
    </array>
</dict>
</plist>

app/views/app_files/new.html.erb
<div class="row">
  <div class="col-md-6">
    <h1>New App File</h1>
    <%= render 'form' %>
  </div>
  <div class="col-md-6">
    <h2>App packaging instructions</h2>
    <h3>If you are not using CocoaPods/frameworks</h3>
    (or if you've never heard of it before)
    <ol>
      <li>
        Open up Terminal.  <code>cd</code> to your Xcode project folder.  Type <code>ls</code> and verify that the folder contains <code><em>YourProjectName</em>/</code> (folder) and <code><em>YourProjectName</em>.xcodeproj</code>, among others. Make sure you see these files. Do not <code>cd</code> any deeper.
      </li>
      <li>
        Run the following command:
        <pre>
xcodebuild clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO</pre>
        This allows you to get a <code>.app</code> file without a developer program. You can find the <code>.app</code> file by going to <code>build/Release-iphoneos/</code> folder. Type:
        <pre>
cd build/Release-iphoneos/</pre>
      </li>
      <li>Upload the resulting <code>.app</code> file.</li>
    </ol>
    <h3>For apps that require CocoaPods/frameworks</h3>
    <ol>
      <li>
        Open up the <code>xcworkspace</code> in Xcode, go to Product > Scheme > New Scheme..., and choose the Target accordingly, and let’s call the Name &ldquo;DukeAppStore&rdquo;.
      </li>
      <li>
        Choose DukeAppStore scheme and click Edit Scheme... And then in Build pane, uncheck everything but &ldquo;Run&rdquo;.
      </li>
      <li>
        Now switch to Run pane, change the Build Configuration to Release.
      </li>
      <li>
        And then run
        <pre>
xcodebuild -workspace <em>YourProject</em>.xcworkspace -scheme DukeAppStore clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO</pre>
      </li>
    </ol>
  </div>
</div>

<%= link_to 'Back', app_path(@app_file.app) %>

app/views/app_files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Platform:</strong>
  <%= @app_file.platform %>
</p>

<p>
  <strong>Version:</strong>
  <%= @app_file.version %>
</p>

<p>
  <strong>Download count:</strong>
  <%= @app_file.download_count %>
</p>

<p>
  <strong>File:</strong>
  <%= @app_file.file %>
</p>

<p>
  <strong>App:</strong>
  <%= @app_file.app %>
</p>

<%= link_to 'Edit', edit_app_file_path(@app_file) %> |
<%= link_to 'Back', app_files_path %>