config/routes.rb
Rails.application.routes.draw do
  resources :apps do
    member do
      get 'latest_version'
    end
    
    resources :app_files do
      get 'build_log'
      get 'download'
    end
  end

  get 'sessions/signin'
  post 'sessions/create'
  get 'sessions/create_during_test'
  post 'sessions/destroy'

  get '/auth/:provider/callback', to: 'sessions#oauth_create'

  root 'apps#index'

end

app/views/apps/_form.html.erb
<%= simple_form_for(@app, html: { class: 'form-horizontal' },
  wrapper: :horizontal_form,
  wrapper_mappings: {
    check_boxes: :horizontal_radio_and_checkboxes,
    radio_buttons: :horizontal_radio_and_checkboxes,
    file: :horizontal_file_input,
    boolean: :horizontal_boolean
  }) do |f| %>
  <%= f.input :name %>
  <%= f.input :description, as: :text %>
  <%= f.input :icon, as: :file, hint: "Your icon will be resized to exactly 512x512.  A 57x57 image will be displayed only during installation on iOS (then replaced by the AppIcon you specified in Xcode)" %>
  <%= f.input :bundle_identifier_suffix, hint: "Used in iOS app signing and manifest generation process.  Your bundle identifier will look like <span id='bundle_identifier_preview'>edu.duke.colab.99_<span id='bundle_identifier_suffix_preview'>YourCustomSuffix</span></span> (&lsquo;99&rsquo; will be replaced by a numerical ID).  This should never be changed once a release is made".html_safe %>

  <%= f.button :submit %>
<% end %>

app/views/apps/edit.html.erb
<h1>Editing App</h1>

<%= render 'form' %>

<%= link_to "Delete App", app_path(@app), method: :delete, class: "btn btn-danger", data: { confirm: 'Are you certain you want to delete this app?' } %>

<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>

app/views/apps/index.html.erb
<h1>Showing all apps</h1>

<div class="row">
  <div class="col-sm-12">
    <p class="lead">Welcome to the Duke App Store. &nbsp;All apps below are free to download for use within the Duke community. &nbsp;Questions? &nbsp;Let us know at <%= link_to 'colab-ops@duke.edu', 'mailto:colab-ops@duke.edu' %></p>
  </div>
</div>
<div class="row app-list">
  <% @apps.each do |app| %>
    <div class="col-sm-6 app-details">
      <div class="row">
        <div class="col-xs-3 app-icon">
          <%= link_to app do %>
            <%= image_tag app.icon.url, :alt => "App logo" %>
          <% end %>
        </div>
        <div class="col-xs-9">
          <div class="caption">
            <h4>
              <%= link_to app.name, app %>
              <small>
                <% if app.author_display_name %>
                  by <%= app.author_display_name %>
                <% end %>
              </small>
            </h4>
            <p>
              <%= link_to 'Details', app, class: 'btn btn-primary btn-sm' %>
            </p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<br>

<% if policy(App).create? %>
  <%= link_to 'New App', new_app_path %>
<% else %>
  <p>Developer? &nbsp;Sign in with your NetID to create new apps.</p>
<% end %>

app/views/apps/new.html.erb
<h1>New App</h1>

<%= render 'form' %>

<%= link_to 'Back', apps_path %>

app/views/apps/show.html.erb
<div id="large_infobox" class="media">
  <div class="media-left">
    <%= image_tag @app.icon.url, :size => "100x100", :alt => "App logo" %>
  </div>
  <div class="media-body">
    <h4 class="media-heading">
      <%= @app.name %>
      <small>
        <% if @app.author_display_name %>
          by <%= @app.author_display_name %>
        <% end %>
      </small>
    </h4>
    <p><%= simple_format @app.description %></p>
    <% if @latest_ios %>
      <p data-no-turbolink>
        <%= link_to @latest_ios.itms_services_url, class: 'btn btn-primary btn-sm btn-download' do %>
          <span class='download-icon'><%= image_tag 'download-icon.png', :size => '17x17' %></span>
          <span>Install on iPhone</span>
        <% end %>
        <p><strong>If this is your first download to iOS 9 or later:</strong> After you download one of our apps on iOS, go to Settings app, tap General > Profile. &nbsp;Under Enterprise App, tap Duke University, and then tap Trust Duke University.</p>
      </p>
    <% end %>
  </div>
</div>

<% if @latest_android %>
<p>
  <%= link_to "Download for Android", app_app_file_download_path(@app, @latest_android) %>
</p>
<% end %>

<%#= debug @latest_ios %>
<%#= debug @latest_android %>

<% if policy(@app).update?  # allow new app file upload if s/he is able to update current app %>
  <%= link_to 'Upload new version of my app', new_app_app_file_path(@app) %>
  |
  <%= link_to 'View all versions of my app', app_app_files_path(@app) %> | 
<% end %>

<% if policy(@app).update? %>
  <%= link_to 'Edit', edit_app_path(@app) %> |
<% end %>

<%= link_to 'Back', apps_path %>