config/routes.rb
Rails.application.routes.draw do
  resources :apps do
    member do
      get 'latest_version'
    end
    
    resources :app_files do
      get 'build_log'
      get 'download'
    end
  end

  get 'sessions/signin'
  post 'sessions/create'
  get 'sessions/create_during_test'
  post 'sessions/destroy'

  get '/auth/:provider/callback', to: 'sessions#oauth_create'

  root 'apps#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App Store &ndash; Innovation Co-Lab &ndash; Duke University</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<div class="container controller_<%= controller_name %> action_<%= action_name %>">
  <div class="header">
    <ul class="nav nav-pills pull-right">
      <li role="presentation">
        <% if current_user.nil? %>
          <%= link_to '/auth/duke_oauth2' do %>
            <span class="glyphicon glyphicon-user"></span>
            Sign in with NetID
          <% end %>
        <% else %>
          <%= link_to sessions_destroy_path, method: :post do %>
            <span class="glyphicon glyphicon-user"></span>
            Log out
          <% end %>
        <% end %>
      </li>
    </ul>
    <div class="brand">
      <%= link_to root_path do %>
	  	  <%= image_tag 'appstore-logo.png', :size => "428x124", :class => 'img-responsive' %>
      <% end %>
    </div>
  </div>

  <%= flash_messages %>

  <%= yield %>

  <div class="footer">
    <p>Innovation Co-Lab App Store version <%= DeployEnv.git_commit %>.</p>
  </div>
</div>

</body>
</html>